name: Validate Source Branch # ワークフローの名前

on:
  pull_request:
    types: [opened, reopened, synchronize] # ワークフローをトリガーするイベントタイプ
    branches:
      - develop # develop ブランチへのプルリクエストを対象

jobs:
  validate:
    runs-on: ubuntu-latest # ワークフローを実行する環境
    name: Validate Source Branch # ステータスチェック名（ブランチ保護ルールと一致させる）

    steps:
      - name: Check out code # ステップの名前（リポジトリのコードをチェックアウト）
        uses: actions/checkout@v3 # コードを取得するアクションを使用

      - name: Validate source branch # ステップの名前（ソースブランチの検証）
        run: | # シェルコマンドを実行
          echo "Base branch: ${{ github.event.pull_request.base.ref }}"  # ベースブランチを表示
          echo "Head branch: ${{ github.event.pull_request.head.ref }}"  # ヘッドブランチを表示

          if [[ "${{ github.event.pull_request.base.ref }}" == "develop" ]]; then
            # develop ブランチへのプルリクエストの場合
            HEAD_REF="${{ github.event.pull_request.head.ref }}"
            if [[ "$HEAD_REF" != feature/* && "$HEAD_REF" != bugfix/* ]]; then
              # ヘッドブランチが feature/* または bugfix/* で始まらない場合
              echo "develop ブランチへの PR は feature/** または bugfix/** ブランチからのみ許可されています。"
              exit 1  # ステータスチェックを失敗させる
            fi
          fi

          echo "ソースブランチの検証に成功しました。"  # 検証成功のメッセージ
