# ブランチ保護ルールを更新するGitHub Actionsのワークフロー

name: Update Branch Protection # ワークフローの名前

on:
  push:
    paths:
      - '.github/branch-protection.yml' # このファイルが変更されたときに実行

jobs:
  update-branch-protection:
    runs-on: ubuntu-latest # ワークフローを実行する環境

    steps:
      - uses: actions/checkout@v3 # リポジトリのコードをチェックアウト

      - name: Apply Branch Protection Rules # ステップの名前
        uses: peter-evans/create-or-update-protection-rule@v4 # ブランチ保護ルールを適用するアクション
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # GitHubトークン（デフォルトで提供されるシークレット）
          repository: ${{ github.repository }} # 対象のリポジトリ（現在のリポジトリ）
          branches: ${{ toJson(fromJson(file('.github/branch-protection.yml')).branches.*.name) }} # 設定ファイルからブランチ名を取得
          protections: ${{ toJson(fromJson(file('.github/branch-protection.yml')).branches.*.protection) }} # 設定ファイルから保護ルールを取得

# ブランチ保護ルールを更新するGitHub Actionsのワークフロー
# name: Update Branch Protection # ワークフローの名前

# # ワークフローをトリガーするイベントを定義
# on:
#   push:
#     paths:
#       - '.github/branch-protection.yml' # このファイルが変更されたときにワークフローを実行

# jobs:
#   update-branch-protection:
#     runs-on: ubuntu-latest # ワークフローが実行される環境（最新のUbuntu）

#     steps:
#       # リポジトリのコードをチェックアウト
#       - uses: actions/checkout@v3

#       # ブランチ保護ルールを作成または更新するステップ
#       - name: Apply Branch Protection Rules # ステップの名前
#         uses: peter-evans/create-or-update-protection-rule@v4 # バージョン4のアクションを使用
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }} # GitHubトークンを指定（デフォルトで提供されるシークレットを使用）
#           repository: ${{ github.repository }} # 対象のリポジトリ（現在のリポジトリ）
#           # 設定ファイルからブランチ名を取得
#           branch: ${{ fromJson(file('.github/branch-protection.yml')).branch }}
#           # 設定ファイルから保護ルールを取得し、JSON形式に変換
#           protection: ${{ toJson(fromJson(file('.github/branch-protection.yml')).protection) }}
